#ifndef	__INC_HARDWARE_H__
#define	__INC_HARDWARE_H__

/*	port and channel	*/
#define	SCL_PORT				GPIO_NUM_16
#define	SDA_PORT				GPIO_NUM_17
#define	NEOPIXEL_LED_PORT		GPIO_NUM_18
#define	FAN_PORT				GPIO_NUM_19
#define	RGBW_LED_R_PORT			GPIO_NUM_21
#define	RGBW_LED_G_PORT			GPIO_NUM_22
#define	RGBW_LED_B_PORT			GPIO_NUM_23
#define	RGBW_LED_W_PORT			GPIO_NUM_4

#define	RGBW_LED_TIMER_MODE		LEDC_HIGH_SPEED_MODE
#define	RGBW_LED_TIMER			LEDC_TIMER_0
#define	RGBW_LED_CH_R			LEDC_CHANNEL_0
#define	RGBW_LED_CH_G			LEDC_CHANNEL_1
#define	RGBW_LED_CH_B			LEDC_CHANNEL_2
#define	RGBW_LED_CH_W			LEDC_CHANNEL_3

#define	FAN_TIMER_MODE			LEDC_HIGH_SPEED_MODE
#define	FAN_TIMER				LEDC_TIMER_1
#define	FAN_CHANNEL				LEDC_CHANNEL_4

// NeoPixel configure
#define	NEOPIXEL_SK6812
#define	NEOPIXEL_RMT_CHANNEL		RMT_CHANNEL_1

//	I2C configure
#define	I2C_FREQUENCY			100*1000
#define	I2C_PORT				I2C_NUM_0

#endif
